name: 'Notify new release to Asfaload'
description: 'Notify Asfaload of a new release to include its checksums in its mirror'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
