name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  notify-asfaload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: issue rest request
        uses: ./
